### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by cyborgdoom** [OpenBotsAI/OpenBots.Server#1]
Can we actually commit a working version... this code does not compile because it has duplicate classes all over the place...

**Comment by cyborgdoom** [comment]
Anyone anyone?

**Comment by cyborgdoom** [comment]
Hello Anyone? I see you working on the other projects... how about getting this to actually compile?

**Comment by openbots-ch** [comment]
Apologies for the delayed response cyborgdoom. We will be pushing the v1.2 code to this GitHub today or tomorrow. The code compiles, although there is some caveats to setting up on the development front to properly view the front/back-end and develop on them. We plan to release a guide on this soon, and streamline the process where possible.

Currently our core development is taking place on another project management platform, but we plan to migrate the Server to GitHub fully to keep it in line with the Studio/Agent.

**Comment by cyborgdoom** [comment]
Thanks that would be awesome...  Looking forward to it.

**Comment by openbots-ch** [comment]
Apologies cyborgdoom, but due to some access issues I won't be able to get the repository up just yet. I was able to get everything ready to go in a local branch, and will respond back here once I am able to push it to remote. Happy Holidays!

**Comment by cyborgdoom** [comment]
No worries... Happy Holidays to you too... Thanks for all your hard work on this project...(all three)

**Comment by openbots-ch** [comment]
Hello @cyborgdoom. I have just pushed up v1.2 into the main branch. I'm getting a clean build on my end. We are currently writing up a guide for getting everything configured for anyone that hasn't worked extensively with similar solutions. If you have trouble getting up and running please let me know.

**Comment by cyborgdoom** [comment]
> Hello @cyborgdoom. I have just pushed up v1.2 into the main branch. I'm getting a clean build on my end. We are currently writing up a guide for getting everything configured for anyone that hasn't worked extensively with similar solutions. If you have trouble getting up and running please let me know.

Thanks... I am not seeing anything has been pushed yet...

**Comment by cyborgdoom** [comment]
Awesome, ok I got everything up and running, however. I can't create a user when looking at the event log I see this

An exception occurred while iterating over the results of a query for context type 'OpenBots.Server.Security.DataAccess.SecurityDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ConcurrencyStamp'.

**Comment by openbots-ch** [comment]
You'll need to adjust the appsettings.json to point to an SQL instance for the server to utilize. From there the migration scripts should handle the setup. If not theres some included SQL scripts as well that can be run.

**Comment by openbots-ch** [comment]
Did all of the migrations go through fine on the connected Database? I would verify that the column exists manually, then execute the included SQL scripts as necessary. The scripts can be found here: https://github.com/OpenBotsAI/OpenBots.Server/tree/main/OpenBots.Server.DataAccess/Migrations

**Comment by cyborgdoom** [comment]
That was it... ran the migrations and now it works...

**Comment by openbots-ch** [comment]
Glad to hear it!

**Comment by cyborgdoom** [comment]
Is there something else I need to know, as when running this, it is really slow starting up.... and most of the time I keep getting a 500 error coz the Angular CLI didn't start in a timely manor ... I personally would not have used Angular ran into too many issues with IE support in the past.... Not a huge reason that this needed to be built as a SPA anyhow...

**Comment by openbots-ch** [comment]
I've posted a Getting Started guide up in the wiki that one of my developers wrote up. That should help with getting everything started up. Generally speaking you will start the front and back-end separately when developing on it (This allows for on the fly modifications to the front end). There's a number of reasons we opted for Angular: familiarity, consistency in implementation, and modularity to name a few. In the long-term we will likely consider Blazor as we push into .NET 5.0, but that's a much larger conversation.

**Comment by cyborgdoom** [comment]
Understood, last time I used Angular was v4 ... and it was a total nightmare as we had to worry about IE 11+ ...  I looked at your getting started guide and duh that makes perfect sense ... I was just running the entire thing via IISExpress ... which was being problematic .

I am actually surprised you didn't go the Blazor route as the original project "Taskt" had a blazor web thing they were doing.... wasn't totally complete but.... Anyhow thank you so much for getting the server piece updated in github and also for building out this RPA ...We are going to be using this where I work, as we use a product called Automate but it has some issues, which were fixed in a later version but we can't upgrade as they changed some things... and licensing is expensive. So we opted to utilize this project.

**Comment by openbots-ch** [comment]
Glad to hear it! TaskT released their Blazor server a bit after we forked, and we decided to prioritize an enterprise grade server, and decided building from scratch was best. Feel free to reach out if you have any questions or issues.
